### ISSUE TITLE
figure out workaround for webkit offset bug

### ISSUE THREAD

**Issue by jfirebaugh** [Leaflet/Leaflet.fullscreen#1]
Same as brunob/leaflet.fullscreen/issues/1

http://code.google.com/p/chromium/issues/detail?id=162549

**Comment by mzachh** [comment]
What do you think about to add the option to force 'leaflet-pseudo-fullscreen'-mode for webkit?

I currently use this solution.

**Comment by jfirebaugh** [comment]
Not seeing this issue in Chrome 47.0.2526.106.
