### ISSUE TITLE
Can't enter full screen when using iframe on Firefox

### ISSUE THREAD

**Issue by leandroprz** [Leaflet/Leaflet.fullscreen#104]
Please go to the end of this page and enter full screen using Chrome (I tested with v78.0.3904.108 (Official Build) (64-bit)):

https://leandroperez.com.ar/en/store/category/timelapse-en/#map

It should enter full screen. But using Firefox it doesn't work (I tested using v71.0 (64-bit)).

I added the map using an iframe. You can check the page [here](https://leandroperez.com.ar/mapa-timelapse/mapa-en.php).

Edit: it doesn't work on Safari 13.0.3 (13608.3.10.10.1) either.

**Comment by Malvoz** [comment]
@leandroprz try adding [`allow="fullscreen"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-allow) (and maybe obsolete [`allowfullscreen`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-allowfullscreen) for wider support) to the iframe.

**Comment by leandroprz** [comment]
Thank you @Malvoz, that did the trick!
