### ISSUE TITLE
feature suggestion: add animation to "zoomToBoundsOnClick" marker clusters

### ISSUE THREAD

**Issue by Llapgochmaster** [Leaflet/Leaflet.fullscreen#13]
As it stands, it is easy for a map user to lose the geographic context when clicking on a map cluster. Adding a smooth zoom-in animation would help people keep their bearings.

**Comment by tmcw** [comment]
This is a plugin for making Leaflet maps fullscreen (hence, Leaflet.fullscreen) - it looks like you're looking for [Leaflet.markercluster](https://github.com/Leaflet/Leaflet.markercluster).
