### ISSUE TITLE
optimized fullscreen icon

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet.fullscreen#14]
I saved the image fullscreen.png with photoshop for web usage - this reduced its size from 7kb to 1kb:

![leaflet fullscreen](https://f.cloud.github.com/assets/158669/1594195/dd6ed034-52d6-11e3-89ee-5547714fcc27.png)

**Comment by tmcw** [comment]
Lossless encoding only shows a ~2% decrease in filesize - are you sure you're not scrunching down the palette of colors?

**Comment by seyfro** [comment]
not really, I saved the image as I always do with web images: photoshop / save for web / select png24; a reduction of the color palette would only occur if I chose png8

**Comment by connor** [comment]
Looks like @tristen just addressed this in 5e773ed8.

**Comment by tristen** [comment]
Yep. Just took the manual approach with these. Closing this for now.
