### ISSUE TITLE
Retina icon?

### ISSUE THREAD

**Issue by connor** [Leaflet/Leaflet.fullscreen#15]
Looks like there's only a 1x icon. @jfirebaugh do you have a vector image or a 2x that we can use to make this not look blurry on a retina machine?

**Comment by jfirebaugh** [comment]
I don't have one handy. @tristen, got any bandwidth to do some icons -- retina and un-fullscreen (#11)?

**Comment by tristen** [comment]
Yeah ... this poor little plugin needs some graphix love. Will hit this.

**Comment by tristen** [comment]
This has been addressed in https://github.com/mapbox/Leaflet.fullscreen/commit/aaccc7f9540f055c6d72b0f5e7c28c1c69bb4fc3 @jfirebaugh can you `npm publish`? I don't seem to have access.

**Comment by connor** [comment]
^:hand: thanks, @tristen!

**Comment by connor** [comment]
Closing out now.
