### ISSUE TITLE
new retina fullscreen icon is not centered

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet.fullscreen#18]
thanks for the update regarding retina fullscreen icon and the support for different icon status depeding on current status (fullscreen on / off).

I just noticed, that the icon is not correctly aligned on retina displays:

![retina-fullscreen-icon-not-centered](https://f.cloud.github.com/assets/158669/1641191/dfa7a742-584c-11e3-9d48-400425707b8e.png)

I fixed this by changing the css for retina fullscreen icon to 

@media
    (-webkit-min-device-pixel-ratio:2), (min-resolution:192dpi) {
        .leaflet-control-fullscreen a {
        background-image:url(images/fullscreen@2x.png);
            background-position: 2px 2px;
        }
        .leaflet-fullscreen-on .leaflet-control-fullscreen a {
            background-position:2px -24px;
        }
}

**Comment by tmcw** [comment]
Can you try updating to v1.5.0 /cc @tristen

**Comment by seyfro** [comment]
v1.5.0 of mapbox.js? doesnt work, I am using leaflet.js ;-)

**Comment by tristen** [comment]
@robertharm what version are you using? It looks like your controls are 30 x 30. These are designed for 26 x 26

**Comment by seyfro** [comment]
I am using leaflet v0.7

**Comment by seyfro** [comment]
just looked again in leaflet.css from leaflet v0.7 - controls on touch devices are 30x30px:

.leaflet-touch .leaflet-bar a {
    width: 30px;
    height: 30px;
    line-height: 30px;
    }

**Comment by leemark** [comment]
I'm also using leaflet 0.7.x and I was noticing the same issue on my android phone. 

I am not convinced it is retina-specific, but instead has to do with the .leaflet-touch CSS posted above (the 30px \* 30px controls). The following CSS (based on yours, @robertharm) resolves the issue for me across mobile platforms, including retina and non-retina devices, android and iOS. 

.leaflet-touch .leaflet-control-fullscreen a {
    background-position: 2px 2px;
}
.leaflet-touch.leaflet-fullscreen-on .leaflet-control-fullscreen a {
    background-position: 2px -24px;
}

Let me know if you want a pull request :)

**Comment by outaTiME** [comment]
:+1:
