### ISSUE TITLE
fullscreenchange event was not correctly listened

### ISSUE THREAD

**Issue by kcwu** [Leaflet/Leaflet.fullscreen#19]
In init hook, you try to listen map's 'load' event.

```
L.Map.addInitHook(function () {
    ...skip...
    this.on('load', function () {
        L.DomEvent.on(document, fullscreenchange, this.
```

However, 'load' event may fired before init hooks are invoked.

leaflet's Map.js

```
                 if (options.center && options.zoom !== undefined) {
                         this.setView(L.latLng(options.center), options.zoom, {reset: true});
                 }
                 ...skip...
                 this.callInitHooks();
```

(setView() will fire 'load')
Thus, fullscreen control will not receive fullscreenchange event if center and zoom are defined.

I'm not sure this is bug of leaflet or Leaflet.fullscreen.

**Comment by jfirebaugh** [comment]
Thanks, good find.

I think Leaflet.fullscreen could use `Map#whenReady` rather than `on('load')`. But I wonder if `initialize` should be reordered, so that `callInitHooks` is guaranteed to be called before `setView`. That would make the order of initialization based on `options.center` and `options.zoom` consistent with `options.layers`, which already happens after `callInitHooks`. @mourner?

**Comment by olizilla** [comment]
Yeah, this caught me out. We init the map with center and zoom options as per the docs: 
http://leafletjs.com/reference.html#map-class

``` js
var map = L.map('map', {
    center: [51.505, -0.09],
    zoom: 13
});
```

and that means the fullscreen plugin doesn't get a chance to listen for the `onfullscreenchange` events, so you can go fullscreen, but you can't come back...

**Comment by olizilla** [comment]
...the quick workaround for anyone else that hits it is to move the center and zoom options to a call to `.setView()` like:

``` js
var map = L.map('map').setView([51.505, -0.09], 13);
```

**Comment by romaopedro** [comment]
use this instead 
map.on('enterFullscreen', function(){
});

map.on('exitFullscreen', function(){
});

**Comment by pouemes** [comment]
hello,

same problem for me
can you explain more how to use 
map.on('enterFullscreen', function(){
});

map.on('exitFullscreen', function(){
});
thanks
