### ISSUE TITLE
Support environments without native fullscreen API

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet.fullscreen#2]
E.g. put the map into body and resize to full extent, reset back on toggle in IE.

**Comment by jfirebaugh** [comment]
Is there a reason why `position: fixed` approach doesn't fully work? Map resizes but new tiles aren't loaded. See above commit.

**Comment by mourner** [comment]
Yes, Leaflet doesn't track map container resize for performance reasons (it only tracks window resize event), so you need to manually call `map.invalidateSize()` after adding or removing the fullscreen class.

**Comment by jfirebaugh** [comment]
Thanks, that was it!
