### ISSUE TITLE
Master branch + tags

### ISSUE THREAD

**Issue by toutpt** [Leaflet/Leaflet.fullscreen#21]
Could you please, create a master branch ? The gh-pages is used for demo / website not to host the sources.

Also could you please create tags per release ?

Theses are common patterns to follow when you release a package so I can easily get a  specific release.

Thanks.

**Comment by tmcw** [comment]
We should definitely start using git tags here, and will do so in the future. There's no reason to have a master branch, and no disadvantages to using `gh-pages` as the main branch.
