### ISSUE TITLE
jslint SyntaxError: invalid property id

### ISSUE THREAD

**Issue by Coroico** [Leaflet/Leaflet.fullscreen#22]
jslint (http://www.javascriptlint.com/online_lint.php) and yui compressor ( http://refresh-sf.com/yui/ ) raises a syntax error with the using of reserved word false/true as property id

1  L.Control.Fullscreen = L.Control.extend({
  2      options: {
  3          position: 'topleft',
  4          title: {
  5              false: 'View Fullscreen',
     ============^
     SyntaxError: invalid property id
  6              true: 'Exit Fullscreen'
  7          }
  8      },
  9  

And may be it could be better to store images in an "images" folder.

A correct yui compressor parsing and an images folder get easier the concatenation of css and js files from leaflet plugins.

**Comment by mourner** [comment]
Wrap reserved words with quotes. This is not a plugin's issue.
