### ISSUE TITLE
fullscreen map not full size

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet.fullscreen#24]
a user of my plugin reported, that when clicking on the fullscreen button, the map doesnt go fullscreen and only displays as large the initial map.
See a demo a htttp://www.livecamcroatia.com/kamere/
I guess this might be a conflict with his theme, as on other installations, the fullscreen button works perfectly with my plugin.
Any hint is appreciated!
thx,

Robert

**Comment by mourner** [comment]
It's a problem with the Google Maps layer - it is not updated on map resize.

**Comment by seyfro** [comment]
thanks
