### ISSUE TITLE
IE11 Native Fullscreen Popups

### ISSUE THREAD

**Issue by CasiOo** [Leaflet/Leaflet.fullscreen#25]
I've tried adding native IE11 fullscreen support to the plugin.
I know it isn't a part of the release, but I hope you guys are still willing to help.

Problems
1) Popups are not placed directly above the markers
2) Leaflet is not giving the popups the correct width. Results in content overflowing the popup

![ie11fullscreen](https://cloud.githubusercontent.com/assets/5333676/3284467/92a4d006-f52b-11e3-938b-1e7d86230048.png)

I've used the following methods and events to add native IE11 fullscreen support:
msRequestFullscreen
msExitFullscreen
msFullscreenElement
MSFullscreenChange

IE11 seems to be going fullscreen, and I'm just having difficulties with the popups

**Comment by jfirebaugh** [comment]
Hard to say what the issue is without the code. Can you provide a pull request?
