### ISSUE TITLE
fullscreen image not displaying - issue with leaflet 0.5.1?

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet.fullscreen#3]
First thanks for your plugin!

I tried to integrate it into my plugin here: http://pro.mapsmarker.com/?p=11
Although I followed the instructions from the readme.txt, it didnt work :-/ As you can see from the screenshot below, the fullscreen control gets added below the zoom control, but unfortunately the background-image defined in leaflet.css is not displayed:

![fullscreen-bug](https://f.cloud.github.com/assets/158669/268530/a134476c-8f3a-11e2-9eb5-e2009d5535a4.png)

Could this be an issue with leaflet 0.5.1?
I´d thankful for any hint on how to solve this!
thanks,

Robert

**Comment by seyfro** [comment]
got it - adding the following css helped:

.leaflet-control-fullscreen a {
    background-image: url(leaflet.fullscreen.png);
    background-position: center center;
    background-repeat: no-repeat;
    width: 21px;
    height: 21px;
    display: block;
}

**Comment by jorgenskogmo** [comment]
For Chrome/Mac, this is also needed:
.leaflet-control-fullscreen {
    position: relative;
    left: 3px;
}
