### ISSUE TITLE
Publish Leaflet.fullscreen in bower packages?

### ISSUE THREAD

**Issue by ChALkeR** [Leaflet/Leaflet.fullscreen#30]
There is currently no entry for Leaflet.fullscreen at http://bower.io/.

**Comment by bdunnette** [comment]
@ChALkeR For what it's worth, you can use bower to install directly from the Github repository, e.g.:

`bower install Leaflet/Leaflet.fullscreen`

http://bower.io/docs/api/#install

Hope that's helpful!

**Comment by jfirebaugh** [comment]
Please use npm+browserify, or install via source.

**Comment by omeid** [comment]
Please push it to bower, leaflet.js is there too, so is many other frontend dev.

**Comment by mourner** [comment]
No.
