### ISSUE TITLE
Leaflet Control Stops Working in Ember App

### ISSUE THREAD

**Issue by wheredoesyourmindgo** [Leaflet/Leaflet.fullscreen#33]
Initially the control will work normally.  After entering new routes in the application, the control appears to stop working at some point. Basically, you can enter fullscreen, but once in fullscreen, you cannot use the fullscreen control (button) to exit.  You can however hit the escape key to exit.  The image on the fullscreen button remains unchanged after entering fullscreen, as if it never entered fullscreen, and the "fullscreenchange" event never fires either.  I've tested the app with a separate fullscreen leaflet control (https://github.com/brunob/leaflet.fullscreen) and the control appears to work all the time, so I'm not certain that it's due to how I've set up my ember component.  

![screen shot 2014-10-12 at 11 59 57 am](https://cloud.githubusercontent.com/assets/3316678/4607139/3be1513a-5242-11e4-9c53-9bbc23e3f6f6.png)

**Comment by ismyrnow** [comment]
I'm using this in an Ember app, and the fullscreen button works across different routes. How are you initializing your map? I am creating my maps through a component, and am not doing anything special for tear-down.

**Comment by wheredoesyourmindgo** [comment]
Thanks for the reply. I should probably close out this issue. I'm not developing anything with Ember or even Leaflet anymore.
