### ISSUE TITLE
full screen z-index issue

### ISSUE THREAD

**Issue by sinanerdem** [Leaflet/Leaflet.fullscreen#34]
When I make a map fullscreen, it automatically takes z-index of a very high value, because there is CSS on the user agent level (Chrome in my case):

webkit-full-screen: 24354663;

This causes any other div on my map to be hidden. Is there a way to avoid this?

**Comment by jfirebaugh** [comment]
You need to make sure that elements you want to remain visible when fullscreen are children of the div that becomes full-screen.

**Comment by hailengc** [comment]
see [**this**](https://stackoverflow.com/questions/18578244/displaying-elements-other-than-fullscreen-element-html5-fullscreen-api) on SO if anyone is still interested in this issue
