### ISSUE TITLE
Leaflet.fullscreen issues with Internet Explorer 11 ?

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet.fullscreen#35]
I am using Leaflet.fullscreen in my WordPress plugin Maps Marker Pro - a user now reported that the fullscreen button does not work properly in IE11. His site is http://www.timebranding.com/ - map at the bottom. If he clicks on the fullscreen button, the map is only partially shown in fullscreen:

![fullscreen-issue](https://cloud.githubusercontent.com/assets/158669/4871247/c5268c44-61a6-11e4-8a09-09dd44230a60.png)

I did some tests with other maps too and found, that fullscreen is working properly with Internet Explorer 8, 9 and 10 - only 11 is causing that issue.

Any hints on how to approach this issue would be very appreciated!

**Comment by jfirebaugh** [comment]
What version are you using?

**Comment by seyfro** [comment]
the latest version (including all current commits) - perhaps this issue has to do with other leaflet plugins I am using too, havent tried leaflet.fullscreen alone on IE11 yet...

**Comment by seyfro** [comment]
I did some more tests - testing the leaflet fullscreen plugin standalone works on IE11 (http://mapsmarker.com/dev/pro/fullscreen/) - so there must be a conflict with some other code of my plugin :-( any hint would really be appreciated...
BTW: the tiles url defined in index.html (http://{s}.tiles.mapbox.com/v3/examples.map-i86knfo3/{z}/{x}/{y}.png) is broken, resulting in blank page after downloading and running the example code from this git repo...

**Comment by jfirebaugh** [comment]
Wait, isn't this the same as #24, which you previously reported?

**Comment by seyfro** [comment]
I dont think so - anyway that old issue cannot be reproduced as the maintainer switched the theme and disabled the fullscreen button.

I also opened a question at http://wpquestions.com/question/showChrono/id/10053 and a user ment that this could be linked with position:abolute; vs. position:relative; - anyway I have to dig deeper to find the real reason for this issue here...

**Comment by seyfro** [comment]
a user just posted a solution that fixed my issues - perhaps this is also interesting for you:

.leaflet-fullscreen-on{
        position:fixed !important;
        width:100% !important;
        height:100% !important;
        top:0 !important;
        left:0 !important;
        z-index:99999;
}

anyway thx for your help!
