### ISSUE TITLE
Map disappearing on closing full-screen with multiple maps

### ISSUE THREAD

**Issue by tinuzz** [Leaflet/Leaflet.fullscreen#36]
I'm not sure how to describe the problem effectively, but let me try. I have a page with two maps on it. Both have a working full-screen button. With the first map, leaving full-screen works fine and takes me back to the page with two maps, but with the second map, it's not OK. After leaving full-screen, the first map is hidden from the page and only the second map is shown.

So I have two map divs:

&lt;div id="tsmap_1" class="leaflet-container leaflet-fade-anim" style="width: 640px; height: 480px; max-width: 100%; position: relative;" tabindex="0"&gt;&lt;/div&gt;
&lt;div id="tsmap_2" class="leaflet-container leaflet-fade-anim" style="width: 640px; height: 480px; max-width: 100%; position: relative;" tabindex="0"&gt;&lt;/div&gt;

According to Firebug, when I click the full screen button on _either_ map, the class parameter of the _first_ map is changed to "leaflet-container leaflet-fade-anim leaflet-fullscreen-on", but the _correct_ map is shown in full-screen. When leaving full-screen from the first map, the 'leaflet-fullscreen-on' class is removed and all is well, but when leaving full-screen from the second map, the class is not removed, the first map-div remains invisible and only the second map (whose class parameter was never changed) is visible.

Also, when entering full-screen for the second map, the button-icon is not changed to the 'leave' icon (with the little square in the middle), like it is on the first map.

So, it seems something is wrong with the selection of the map container when manipulating the DOM, but I can't tell what's wrong by looking at the code. Not enough JavaScript skillz I'm afraid.

The behaviour is the same in FF 34 and Chrome 39 on Windows.

**Comment by tinuzz** [comment]
A live example can be found here: https://www.grendelman.net/wp/leaflet-fullscreen-test/
To test, go to full-screen on the second map and back.

Map initialization is done here:
https://www.grendelman.net/wp/wp-content/plugins/wp-trackserver/trackserver-maps.js

**Comment by jfirebaugh** [comment]
This was fixed in 259ac31aec8bdac184df64d9056c41b269e74547 but never released. I've just released v0.0.4 with the fix.

**Comment by tinuzz** [comment]
Great, thanks!!
