### ISSUE TITLE
Lincense properties do not match

### ISSUE THREAD

**Issue by billymoon** [Leaflet/Leaflet.fullscreen#37]
Appears to be a BSD license in project, but `package.json` reports `MIT`.

**Comment by IvanSanchez** [comment]
Nope, `package.json` explicitly refers to the 2-clause BSD: https://github.com/Leaflet/Leaflet/blob/master/package.json#L38

**Comment by IvanSanchez** [comment]
You're confusing https://github.com/brunob/leaflet.fullscreen with https://github.com/Leaflet/Leaflet.fullscreen - license information in the latter (this repo) is OK.
