### ISSUE TITLE
Suggestion: hide fullscreen button on Android

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet.fullscreen#4]
I checked your demo map on Android 4.2.2/Nexus with Chrome and Firefox - fullscreen mode doesnt work here.
Is there a way to hide the button if pseudo-fullscreen-mode is also not supported?
Thx,

**Comment by tmcw** [comment]
It should be supported instead. Will test this out on an android device in a bit.

**Comment by seyfro** [comment]
tested it again, works now - must have been a temporary issue
