### ISSUE TITLE
No response on Apple devices

### ISSUE THREAD

**Issue by geospatialem** [Leaflet/Leaflet.fullscreen#42]
The Leaflet.fullscreen works as-expected on Windows and Android devices, however it does not work on Apple devices (iPad and iPhone) across multiple browsers (e.g. Safari and Chrome).

However, using developer tools in emulation mode the button works as-expected.

Anyone else encounter this as well, or know why this may be happening?

**Comment by jfirebaugh** [comment]
No one else has reported this issue; I assume it is something specific to your page. If you are still encountering it, please provide a minimal self-contained example that demonstrates the issue.

**Comment by GWillmann** [comment]
For future reference, make sure you checkout what fullscreen actually does on iPhone devices by visiting https://leaflet.github.io/Leaflet.fullscreen/ with your iPhone.

You will see that fullscreen mode only stretches the map to the edges of the webpage without hiding the status bar the tab bar etc...
