### ISSUE TITLE
Conflict with mapbox.geocoderControl in Safari

### ISSUE THREAD

**Issue by fitnr** [Leaflet/Leaflet.fullscreen#43]
Showing a map on full screen disables a `mapbox.geocoderControl` in Safari (v9.0 in OS X 10.11).

To reproduce, see this example: `http://bl.ocks.org/fitnr/raw/47d0c8d1653c88dc7ac5/`. Click to make full screen, then try to use the geocoder.

This is obviously a Safari bug, but I wanted to drop it here just in case someone can find an easy fix.

**Comment by jfirebaugh** [comment]
I can reproduce the issue, but as you note this looks like a browser bug and I doubt there's a fix from the Leaflet.fullscreen side.
