### ISSUE TITLE
Demo missing

### ISSUE THREAD

**Issue by yohanboniface** [Leaflet/Leaflet.fullscreen#47]
https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md#demo.

**Comment by jfirebaugh** [comment]
http://leaflet.github.io/Leaflet.fullscreen/ -- linked next to the description.

**Comment by yohanboniface** [comment]
oh, my bad :)
I'd suggest to add it to the README for blind people like me ;)
