### ISSUE TITLE
Suggestion: add fallback styles for IE 8

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet.fullscreen#5]
I added this to leaflet.ie.css - otherwise on IE 8 (or smaller), the fullscreen image is on a transparent background - see image below:

![mapbox-fullscreen-ie8-styles-fallback](https://f.cloud.github.com/assets/158669/272063/545509d6-8ff8-11e2-9e6c-4779f33239ee.jpg)

`.leaflet-control-fullscreen a {
    background: #eeeeee;
    background-image: url("images/fullscreen.png");
    background-position: center center;
    background-repeat: no-repeat;
    border: #999 2px solid;
}`

**Comment by jfirebaugh** [comment]
Is this with Leaflet 0.5.1? So far we've only really tested Leaflet master (future 0.6.0).

**Comment by seyfro** [comment]
Leaflet 0.5.1

**Comment by tristen** [comment]
With https://github.com/Leaflet/Leaflet/issues/2159 I think its safe to close this.
