### ISSUE TITLE
Modal window does not appear on fullscreen mode

### ISSUE THREAD

**Issue by maydemirx** [Leaflet/Leaflet.fullscreen#54]
Maybe this is not your problem. But i want to explain my problem. After chrome and firefox updates, the modal window doesn't appear on top of the page when i switched to fullscreen mode. Can any one help me?

**Comment by a1an77** [comment]
What do you mean by modal window? If you don't publish a demo to reproduce the problem it is quite difficult to investigate your problem or give any advice

**Comment by maydemirx** [comment]
OK.

i am trying to explain my problem with the [demo](https://leaflet-tag-filter-button.herokuapp.com/fullscreen.html)

i wrote the problem step by step on demo site at bottom of the page.

**Comment by a1an77** [comment]
I can confirm this issue and I also had problems showing modal elements in full screen mode. No idea if that would be an issue with this plugin or a conflict in full screen browser capability. Did you try the https://github.com/mapshakers/leaflet-control-window plugin? If I remember correctly it works as modal even in fullscreen

**Comment by kipp0** [comment]
You can achieve what you want by setting your modal's z-index

`z-index: 999999999999999999999999999;`

**Comment by maydemirx** [comment]
@kipp0 no sorry. This way is not working!

**Comment by maydemirx** [comment]
@a1an77 leaflet-control-window is working no problem. But modal backdrop (semi-transparent black div) is not covering the whole page when fullscreen mode is not enabled.

**Comment by maydemirx** [comment]
This issue is related to HTML-fullscreen api. Because chrome,firefox,ie vs set to z-index of fullscreen container div to max number value. (2147483647).

You can see list of max z-index property for modern browsers at: http://www.puidokas.com/max-z-index/

**Comment by a1an77** [comment]
So, since the only reference to z-index in this plugin is only in pseudo-fullscreen and it is well below the limit:
https://github.com/Leaflet/Leaflet.fullscreen/blob/f5e76270ad40bb573bd11595f9069c3f15f8f286/dist/leaflet.fullscreen.css#L31

Looks like nothing can be done about it here and you likely have to open an issue on the modal provider maintainer, right? Or make the modal a sub-element of the map I guess...

PS: Or would it be possible to lower that value via css in this plugin?

**Comment by maydemirx** [comment]
@a1an77 leaflet.fullscreen use to [HTML5 fullscreen api ](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API). So, this is not related to leaflet.fullscreen css. I thing there is no way to bringing modal to top of the order. Thanks for your helps.

**Comment by ventralnet** [comment]
If you are using angular ui bootstrap modal, you can use the 'appendTo' option to specify to specify an element to append to.  In this case you want to append the modal to your map div.  By default the modal is appended to the body element.  This should resolve your issue..

**Comment by lumantovanini** [comment]
@ventralnet This work for me! Thanks!

**Comment by Amir-Pasha-Bagheri** [comment]
I am facing the same issue but in React !

any solution for me ?
