### ISSUE TITLE
Supported leaflet versions

### ISSUE THREAD

**Issue by jekuno** [Leaflet/Leaflet.fullscreen#55]
As the release of Leaflet 1.0 is nearly final now:
Maybe you could add a note to the README which leaflet versions currently are supported by your plugin. That would help users who plan to update from Leaflet 0.7.x to 1.0. :)

**Comment by jfirebaugh** [comment]
Added in 0c599cf4f369ee50658dc6a77b6082e239fd4f9c.

**Comment by jekuno** [comment]
Thanks.
