### ISSUE TITLE
CSS Issue

### ISSUE THREAD

**Issue by BourbonCrow** [Leaflet/Leaflet.fullscreen#56]
Fullscreen with 'pseudoFullscreen': false didnt work as it should in chrome (didn't test other browsers)

faulty line
`.leaflet-container.leaflet-fullscreen-on {`

was a space missing

should be

`.leaflet-container .leaflet-fullscreen-on {`

then it all works

**Comment by jfirebaugh** [comment]
I don't think the change you're proposing is correct. `.leaflet-container` and `.leaflet-fullscreen-on` are applied to the same element, therefore they should not have a space in the CSS.
