### ISSUE TITLE
Feature suggestion: closing pseudo fullscreen map on button click/escape

### ISSUE THREAD

**Issue by seyfro** [Leaflet/Leaflet.fullscreen#6]
When entering fullscreen mode on Safari for example, there is no way to exit the fullscreen mode again. You have to reload the page in order to see the normal map again.

**Comment by jfirebaugh** [comment]
What I'm seeing is that Safari (v6) supports native fullscreen, and even in browsers that don't, the fullscreen button is visible in pseudo-fullscreen and can be clicked again to exit. Are you seeing otherwise?

**Comment by seyfro** [comment]
I am Windows user - so can only test with 5.1.7 where clicking the fullscreen button again doesnt have any effect...

**Comment by frontendplace** [comment]
when I have two maps on one page the fullscreen mode gets mixed up. I call the toggleFullscreen function on the first map and have the correct container but the _onFullscreenChange function detects the second map as container. temporary I use the pseudo-fullscreen by commenting out the fullscreen code when i have two maps. that works great. 
But now I try to use the escape key to close the pseudo fullscreen map. 

added this:
in the onAdd:
L.DomEvent.on(document, 'keyup', this._keyUp, this);
and added
_keyUp: function (e) {
        if (e.keyCode == 27 && this._map._isFullscreen) { 
            this._map.toggleFullscreen();
        }
    },

also then it works when i have one map but when i have two maps only the second map closing works. I am also stuck here. Maybe some idea?

**Comment by jfirebaugh** [comment]
@frontendplace That's a different issue. Can you please open a separate ticket?

**Comment by jfirebaugh** [comment]
Not reproducible.
