### ISSUE TITLE
Invalidate map size on fullscreen toggle

### ISSUE THREAD

**Issue by zuck** [Leaflet/Leaflet.fullscreen#60]
On my map I'm using a GeoJSON layer and custom CSS margin to locate it on the page.

When I switch to fullscreen mode, the GeoJSON layer doesn't display shapes correctly, still taking in consideration the old CSS margin (but actually removed by CSS when the map is fullscreen).

The only fix I found is to fire a `map.invalidateSize()` when the `fullscreenchange` event is emitted.

**Comment by jfirebaugh** [comment]
Thanks for the report @zuck. Want to submit a PR that adds `invalidateSize()` to [`_setFullscreen`](https://github.com/Leaflet/Leaflet.fullscreen/blob/f5e76270ad40bb573bd11595f9069c3f15f8f286/dist/Leaflet.fullscreen.js#L89)?
