### ISSUE TITLE
t.addTo is not a function

### ISSUE THREAD

**Issue by StefanBrand** [Leaflet/Leaflet.fullscreen#62]
Hi, I tried `map.addControl(L.Control.Fullscreen);`, but Firefox console gives me `t.addTo is not a function`. The fullscreen button is not added to the map.

I cannot use the `fullscreenControl: true` option because I want to add the fullscreen button only in a specific case.

**Comment by jfirebaugh** [comment]
Can you please create a minimal self-contained example that demonstrates the issue?

**Comment by StefanBrand** [comment]
Thanks for the fast reply! Wait a second

Edit: You can check it out here:

https://stefanbrand.github.io/fprsmap/

I added the line [here](https://github.com/StefanBrand/fprsmap/commit/7437a0288491a55744459841e25902ece261d4b1#diff-77ab163850ef0fa98d6a9ee9fb6bbcafR117).

**Comment by StefanBrand** [comment]
Could you check it out?

**Comment by jfirebaugh** [comment]
I don't see any errors when I load that page. Do I need to do something to trigger the issue?

**Comment by StefanBrand** [comment]
Sorry, I had  to outcomment the issue for production. It's in line 113 of main.js.
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 22. Februar 2017 19:09:01 MEZ schrieb John Firebaugh <notifications@github.com>:
>I don't see any errors when I load that page. Do I need to do something
>to trigger the issue?

**Comment by jfirebaugh** [comment]
Ok, can you please set up a standalone demo that reproduces the issue, that's independent of your production deployment? I'd like to help you, but in return I'm asking for you to make it easy to do so.

**Comment by StefanBrand** [comment]
It was quite easy for two days or so. ;-) I just wanted to make some progress, so I outcommented the lines there for now.

Here you go: https://stefanbrand.github.io/leafletfullscreentest/ (Repo is here: https://github.com/StefanBrand/leafletfullscreentest ). In the developer console of your browser (tested on Firefox 51.0.1) you can easily see the error message.



PS.: I was put off from setting up an own repo for this, but eventually it was easier than I had thought...

**Comment by jfirebaugh** [comment]
Thanks, now I see the issue: `mymap.addControl(L.Control.Fullscreen);`. This should be `mymap.addControl(new L.Control.Fullscreen());` In  22141a4a2224e0fab02ce37d6472c92f6d9d03de, I've clarified this in README.md.

**Comment by StefanBrand** [comment]
Thank you! The README is very clear now! :) 

Edit: The fullscreen button has returned and looks beautiful! 😍 

See: https://stefanbrand.github.io/fprsmap/
