### ISSUE TITLE
fullscreenElement doesn't get changed if map is refreshed

### ISSUE THREAD

**Issue by VidhyaApple** [Leaflet/Leaflet.fullscreen#65]
I use `leaflet3.js` and `leaflet-fullscreen-min.js` In map, I have fullscreen control button to toggle between maximize and minimize. If page reloads, everthing works fine. But if only map div reloads, `fullscreenElement` doesn't get updated with new div.

 [This reference](https://msdn.microsoft.com/en-us/library/dn254937(v=vs.85).aspx) states that - **If there's more than one element in the full-screen mode element stack, then this property returns the top element**. 

So when map div refreshes, `fullscreenElement` doesn't get updated with new one. This is a bug in `leaflet3.js`

when map in minimized state, it displays maximize icon (This is ok)
![screenshot_2017-06-08_10-52-25](https://user-images.githubusercontent.com/7392482/26914607-e5dc627a-4c3f-11e7-9f6f-cc29b0e75550.png)
So once map is maximized, icon doesn't change to minimize button
![screenshot_2017-06-08_10-56-26](https://user-images.githubusercontent.com/7392482/26914624-fab7e3a4-4c3f-11e7-8243-8efbdf09e1d0.png)
Problem is, `fullscreenElement` doesn't get changed if a page has more than one map (ie. div reloads with same map again which is not reflected in `fullscreenElement`).

What would be the solution for this?

**Comment by jfirebaugh** [comment]
Not sure I understand the steps involved here. Could you please create a minimal standalone example on JSFiddle that demonstrates the issue?

**Comment by jfirebaugh** [comment]
No response; closing.
