### ISSUE TITLE
Control icon is not a full screen icon

### ISSUE THREAD

**Issue by completer** [Leaflet/Leaflet.fullscreen#66]
Hello, I don't think I've ever seen a full screen icon that looks like the current pair of icons used for this control (which look more like a target or selector).

What would be the way to change it to something that made more sense to users? For example, to: http://fontawesome.io/3.2.1/icon/fullscreen/

**Comment by IvanSanchez** [comment]
Well, there are precendents of icons like the one used, see e.g. https://materialdesignicons.com/icon/fullscreen 

The way to override the icon is to override [this CSS rule](https://github.com/Leaflet/Leaflet.fullscreen/blob/gh-pages/dist/leaflet.fullscreen.css#L2). If you can come up with another way of specifying the icon, feel free to suggest it in the form of a pull request.

**Comment by seyfro** [comment]
FYI - I made 2 alternative icon sets for my plugin www.mapsmarker.com, feel free to use it (just use the proper credits and license, which is P.J. Onori, http://somerandomdude.com, Creative Commons Attribution Share Alike (by-sa)

![fullscreen 1x](https://user-images.githubusercontent.com/158669/27448401-f828ba50-5784-11e7-889e-a607591d25d5.png)
![fullscreen 2x](https://user-images.githubusercontent.com/158669/27448402-f82b6e30-5784-11e7-8c66-8d7729504a65.png)

![fullscreen 1x-light](https://user-images.githubusercontent.com/158669/27448411-fdbda5f2-5784-11e7-8f4f-d4e7b20f6616.png)
![fullscreen 2x-light](https://user-images.githubusercontent.com/158669/27448412-fdc67d12-5784-11e7-98b2-2eb6e66330dd.png)
