### ISSUE TITLE
When fullscreen mode has been exited map center shifts

### ISSUE THREAD

**Issue by wingertjp** [Leaflet/Leaflet.fullscreen#68]

**Comment by jfirebaugh** [comment]
I don't see this effect on http://leaflet.github.io/Leaflet.fullscreen/. Could you please provide a minimal self contained demo that shows the issue?

**Comment by wingertjp** [comment]
Yes look at 
https://prix-des-carburants.com/station-service/total-toulon-83000010

**Comment by jfirebaugh** [comment]
Maybe I'm missing what you're talking about, but I don't see the center changing there either. Also, it's not what I mean by "minimal self-contained demo" -- I mean a standalone example on JSFiddle or similar that doesn't have any application-specific code. (My time is limited, so in exchange for it I ask that you make it as easy for me as possible to determine if this is actually a bug in Leaflet.fullscreen, or something else -- bug in your application, browser bug, etc.)

**Comment by wingertjp** [comment]
Ok I'll post a self contained demo soon, thx for your reactivity
