### ISSUE TITLE
Bootstrap modal does not work

### ISSUE THREAD

**Issue by cccruzr** [Leaflet/Leaflet.fullscreen#69]
Don't know if it is relevant enough, however I would like to report it, despite I solved the problem with instructions from [stack**overflow**](https://stackoverflow.com/questions/36672561/how-to-exit-fullscreen-onclick-using-javascript):

I have a bootstrap modal popup associated to a button, however it doesn't work in `map.fullscreen` mode but works correctly in `F11` browser's default fullscreen mode.

EDIT: Despite I solved the problem

**Comment by jfirebaugh** [comment]
Sounds like you solved the issue, but if not, please provide a minimal, self-contained example that demonstrates the issue.
