### ISSUE TITLE
Styles not applying when installing 'leaflet-fullscreen' as a package

### ISSUE THREAD

**Issue by gitjul** [Leaflet/Leaflet.fullscreen#72]
When I'm adding the plugin using yarn the script works but the styles aren't applied. When loading via CDN or dropping the files directly in my app all is good.
Other leaflet plugins such as leaflet-draw work ok.

**Comment by jfirebaugh** [comment]
Hi @gitjul. The CSS is provided [here](https://github.com/Leaflet/Leaflet.fullscreen/blob/gh-pages/dist/leaflet.fullscreen.css). You'll need to consult the documentation for the tools you're using (e.g. webpack) to determine how to include that in your application.

**Comment by gitjul** [comment]
@jfirebaugh Hi! I noticed that file and I was expecting it to be loaded. But now I noticed that it wasn't set up in my project and all the leaflet styles are actually linked (from a cdn) in a separate file. I'll look into setting up css loading using webpack. So thanks!

Btw, what do you mean by "these two rules" in the part below?

```
/* Do not combine these two rules; IE will break. */
.leaflet-container:-webkit-full-screen {
  width:100%!important;
  height:100%!important;
  }
.leaflet-container.leaflet-fullscreen-on {
  width:100%!important;
  height:100%!important;
  }
```

**Comment by gitjul** [comment]
Also, sorry but where is the `.svg` file used? I don't see any relevant rule in the styles, was this an improvement you were planning?

**Comment by jfirebaugh** [comment]
> Btw, what do you mean by "these two rules" in the part below?

It refers to the `.leaflet-container:-webkit-full-screen` and `.leaflet-container.leaflet-fullscreen-on` rules. They can't be combined as `.leaflet-container:-webkit-full-screen, .leaflet-container.leaflet-fullscreen-on`.

I believe the svg file is the original source for the png. It's included in case somebody wants to modify the icons in the future, but not used at runtime.
