### ISSUE TITLE
Problem with sidebar (disappears)

### ISSUE THREAD

**Issue by ludovico85** [Leaflet/Leaflet.fullscreen#73]
Hi,
I've used the sidebar v2 https://github.com/Turbo87/sidebar-v2 to add a sidebar to my map. In full screen mode (as implemented by the leaflet.fullscreen) the sidebar disappear.
A similar issue was highlighted here https://github.com/Turbo87/sidebar-v2/issues/19 ad seems to be a problem related with the fullscreen instead of the sidebar directly.

Is there a solution?

Thank you

**Comment by jfirebaugh** [comment]
The sidebar must be a child of the map container element (the one with the `leaflet-container` class).
