### ISSUE TITLE
Add provision to add the custom icon

### ISSUE THREAD

**Issue by vamsikrishnamannem** [Leaflet/Leaflet.fullscreen#75]
Now, I can't change the zoom in and zoom out icon, Can you give configuration options for change the zoom in and zoom out icons.

![capture](https://user-images.githubusercontent.com/7932747/36667903-863cfe88-1b15-11e8-9022-0a4d8c224378.JPG)

**Comment by jfirebaugh** [comment]
I'm not sure what you are asking for here. Could you please fill out the description?

**Comment by jfirebaugh** [comment]
Sure, replace [`fullscreen.png`](https://github.com/Leaflet/Leaflet.fullscreen/blob/gh-pages/dist/fullscreen.png) (and `fullscreen@2x.png`) with the icons you want.
