### ISSUE TITLE
Fullscreen not working

### ISSUE THREAD

**Issue by dave7777** [Leaflet/Leaflet.fullscreen#76]
for some reason in the fullscreen view the upper part of the screen is filled with the black background - I have attachedthe screenshot.....do you think this is a bug?

<a href="http://tinypic.com?ref=4vlcus" target="_blank"><img src="http://i64.tinypic.com/4vlcus.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by dave7777** [comment]
.I did a quick check and it appears the page sections are below that black area:

<a href="http://tinypic.com?ref=2vdl1g9" target="_blank"><img src="http://i68.tinypic.com/2vdl1g9.png" border="0" alt="Image and video hosting by TinyPic"></a>

this is ok? maybe some other plugin will work?

**Comment by jfirebaugh** [comment]
Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?

**Comment by dave7777** [comment]
Thank you for your kind reply.... I have attached the local version of the webpage on which I am working....

https://sendit.cloud/77zvt6g0ajgh

here is how it shows on my side:

<a href="http://tinypic.com?ref=33dbeb5" target="_blank"><img src="http://i68.tinypic.com/33dbeb5.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by jfirebaugh** [comment]
Hi @dave7777, by "minimal self-contained example", I mean an example that contains the minimal amount of code necessary to demonstrate the issue. The archive you provided contains dozens of files and thousands of lines of code, so is not minimal. A minimal example will allow me to spend time tracking down the issue without looking through irrelevant details, and eliminate the possibility that the issue lies in something other than Leaflet.fullscreen.

**Comment by dave7777** [comment]
yes....I guess I cannot condense this any further - I spent an hour removing other elements of the webpage...I guess hti has to do with the pase templaet itself...you still cannot check this page tyo see what might be the cause for this?

**Comment by dave7777** [comment]
Thank you for your reply.....I removed most fo what I think I can remove from this file...please take a look - I uplaoded the updated demo page

https://sendit.cloud/85z1skduim37

**Comment by jfirebaugh** [comment]
It looks like it's due to custom CSS, particularly `position: absolute;` and an absolute top and left coordinate on the map container. You'll need to ensure that the CSS you apply is compatible with a full screen layout. Closing here since this isn't an issue with the plugin itself.

**Comment by dave7777** [comment]
thank you very much - I am not that a coder - can you please tell me weher this code is located?
