### ISSUE TITLE
How can I set up some div which isn't the component of the leaflet on the map ?

### ISSUE THREAD

**Issue by ghost** [Leaflet/Leaflet.fullscreen#85]
How can I set up some div which isn't the component of the leaflet on the map ?I can't modify the zIndex of the map to do that

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by ghost** [comment]
Thanks,I just write some methods to implements it,without this plugin
