### ISSUE TITLE
Top right position

### ISSUE THREAD

**Issue by peter450** [Leaflet/Leaflet.fullscreen#89]
Thank you for this plug-in.
Can you explain me how to put the full view (and also the zoom) buttom in the `<div class="leaflet-top leaflet-right">` unstead the `<div class="leaflet-top leaflet-left">` and by the way in the bottom ?
I don't want to change the css file for this.
Best regards.

**Comment by peter450** [comment]
Thank you for this plug-in.
Can you explain me how to put the full view (and also the zoom) buttom in the `<div class="leaflet-top leaflet-right">` unstead the `<div class="leaflet-top leaflet-left">` and by the way in the bottom ?
I don't want to change the css file for this.
Best regards.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
