### ISSUE TITLE
Move Full Screen Button to Bottom Right

### ISSUE THREAD

**Issue by Stephen-Jawahar** [Leaflet/Leaflet.fullscreen#92]
Is there a way to move the full screen button to a different position other than the default top left of the leaflet map. If there is a way can someone explain it to me. Thanks

**Comment by IvanSanchez** [comment]
https://leafletjs.com/reference-1.4.0.html#control-position

**Comment by Stephen-Jawahar** [comment]
> https://leafletjs.com/reference-1.4.0.html#control-position

Hi, I am new to this, do I need to change the position type in the node module code itself or is there a way to change it dynamically for each instance when it is used. If there is a way to change it dynamically for each instance of use in an application, can you give me the code to implement it that way. 

thanks

**Comment by IvanSanchez** [comment]
Experiment with other leaflet controls (e.g. `L.Control.Layers`, `L.Control.Scale`) and see how they're put in other corners. It's the same for the fullscreen control.
